describe('Checkout - Sauce Demo',()=>{
    beforeEach(()=>{
        cy.visit('https://www.saucedemo.com/')
        cy.get('[data-test="username"]').type('standard_user')
        cy.get('[data-test="password"]').type('secret_sauce')
        cy.get('[data-test="login-button"]').click()
        cy.url().should('include','/inventory.html')
    })

    it('Completar checkout con datos válidos',()=> {
        cy.get('#item_2_title_link').scrollIntoView()
        cy.get('[data-test="add-to-cart-sauce-labs-onesie"]').click()
        cy.get('[data-test="remove-sauce-labs-onesie"]').should('be.visible')
        cy.get('.app_logo').scrollIntoView()
        cy.get('[data-test="shopping-cart-link"]').click()
        cy.get('[data-test="checkout"]').click()
        cy.get('[data-test="firstName"]').type('Juan')
        cy.get('[data-test="lastName"]').type('Pérez')
        cy.get('[data-test="postalCode"]').type('5000')
        cy.get('[data-test="continue"]').click()
        cy.get('[data-test="payment-info-value"]').should('be.visible')
        cy.get('[data-test="finish"]').click()
        cy.get('[data-test="complete-header"]')
        .should('be.visible')
        .and('contain','Thank you for your order!')
    })

    it('Checkout sin completar campos obligatorios',()=> {
        cy.get('#item_2_title_link').scrollIntoView()
        cy.get('[data-test="add-to-cart-sauce-labs-onesie"]').click()
        cy.get('[data-test="remove-sauce-labs-onesie"]').should('be.visible')
        cy.get('.app_logo').scrollIntoView()
        cy.get('[data-test="shopping-cart-link"]').click()
        cy.get('[data-test="checkout"]').click()
        cy.get('[data-test="continue"]').click()
        cy.get('[data-test="error"]')
        .should('be.visible')
        .and('contain','Error: First Name is required')
    })

})